<a href="https://colab.research.google.com/github/Staywithtatar/Project/blob/main/Naive_Bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris

In [ ]:
data=load_iris()

In [ ]:
data.data.shape

(150, 4)

In [ ]:
data

In [ ]:
print('คุณลักษณะ',data.feature_names)

คุณลักษณะ ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [ ]:
print('ชื่อสายพันธ์',data.target_names)

ชื่อสายพันธ์ ['setosa' 'versicolor' 'virginica']


In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x=data.data
y=data.target

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(data.data,data.target,test_size=0.3,random_state=50)

In [ ]:
from sklearn.naive_bayes import GaussianNB
clf=GaussianNB()

In [ ]:
clf.fit(x_train,y_train)

GaussianNB()

In [ ]:
y_pred=clf.predict(x_test)
print(y_pred)

print(y_test)

[1 1 0 0 2 2 2 0 0 1 0 2 0 2 1 0 1 0 1 2 2 1 0 2 1 2 1 1 1 2 2 1 1 2 0 0 1
 1 1 0 0 1 2 0 2]
[1 1 0 0 2 2 2 0 0 1 0 2 0 2 1 0 1 0 1 1 2 1 0 2 1 2 1 1 1 2 2 1 1 2 0 0 1
 2 1 0 0 1 2 0 2]


In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
print('ค่าความแม่นยำ:',accuracy_score(y_test,y_pred))

ค่าความแม่นยำ: 0.9555555555555556


In [ ]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[14  0  0]
 [ 0 16  1]
 [ 0  1 13]]
